### ISSUE TITLE
Duplicate of another open source library without giving credits

### ISSUE THREAD

**Issue by aiavci** [whylabs/openllmtelemetry#5]
This looks like a duplicate of another open source library that has a clear license. I recommend either deleting this or following appropriate steps to give credit.

**Comment by andyndang** [comment]
Thanks for raising this. We are still pushing code out and will definitely add credit to the @openllmetry package at the top of the files - we do not intent to mislead the OSS community

**Comment by ggoonnzzaallo** [comment]
Not just duplicated another open source lib without giving credit, but also basically copied their name. Is this really how WhyLabs conducts business?

**Comment by andyndang** [comment]
Hi @ggoonnzzaallo ! Our package goal is very different from what traceloop's openllmetry does - and our namespaces don't collide in terms of pypi (traceloop and opentelemetry-* prefix). The purpose of this package and what traceloop does is very different.
